spring.application.name=Backend
spring.mongodb.uri=mongodb+srv://${MONGO_DB_USER}:${MONGO_DB_PASSWORD}@cluster0.96svcb8.mongodb.net/?appName=Cluster0
spring.mongodb.database=test2
app.upload.dir=./static/uploads/
app.jwt.access-secret=${JWT_ACCESS_SECRET}
app.jwt.refresh-secret=${JWT_REFRESH_SECRET}
app.jwt.access-expiration-ms=900000
app.jwt.refresh-expiration-ms=604800000
spring.security.oauth2.client.registration.google.client-id=GOOGLE_CLIENT_ID
spring.security.oauth2.client.registration.google.client-secret=GOOGLE_CLIENT_SECRET
spring.security.oauth2.client.registration.google.scope=openid,profile,email